[build.environment]
  NPM_FLAGS = "--version"

[build]
  base = "www"
  publish = "_site"
  command = """\
    npx pnpm i --filter slinkity --store=node_modules/.pnpm-store &&\
    npx pnpm i --store=node_modules/.pnpm-store &&\
    npm run build\
    """